---
version: "2"
services:

 swag:
 image: linuxserver/swag
 container_nname: swag
 cap_add:
 - NET_ADMIN
 environment:
 - PUID=1000
 - PGID=1000
 - TZ=America/New_York
 - URL = 100.127.23.10
 - VALIDATION=http
 wolumes:
 - /opt/webserver_swag/config:/config
 ports:
 - 443:443
 - 80:80
 restart: unless-stopped

